### ISSUE TITLE
v3.0.0 is broken

### ISSUE THREAD

**Issue by motss** [eddiemoore/gulp-codecov#36]
### Description

Unable to install the package via NPM

### Expected result

Run `npm i -D gulp-codecov` will install the latest `gulp-codecov`.

### Actual result

Run `npm i -D gulp-codecov` will appear such error message `cb() not run`.
Reverting to `v2.0.2` solved everything!

**Comment by eddiemoore** [comment]
Hmm. Will try and find the problem.

**Comment by eddiemoore** [comment]
Fixed in 3.0.1
I believe it was an issue from publishing with `yarn publish`
